### ISSUE TITLE
example data files are missing

### ISSUE THREAD

**Issue by tolot27** [TAMU-CPT/mauved3#12]
It would be great to have all required data files included in the repository to get the example working.

Currently, the JSON files `example/nucl.json` and `example/prot.json` point to the following files which do not exist in the repository:
```
data/[nucl|prot]/CbK.txt
data/[nucl|prot]/Colossus.txt
data/[nucl|prot]/Karma.txt
data/[nucl|prot]/Magneto.txt
data/[nucl|prot]/Rogue.txt
data/[nucl|prot]/Swift.txt
data/[nucl|prot]/CbK.gff
data/[nucl|prot]/Colossus.gff
data/[nucl|prot]/Karma.gff
data/[nucl|prot]/Magneto.gff
data/[nucl|prot]/Rogue.gff
data/[nucl|prot]/Swift.gff
data/[nucl|prot]/regions.json
```

Also, the link text in `example/README.md` do not match the link URL.

**Comment by hexylena** [comment]
Hi @tolot27, if you `rm example/*.json`, and then `make examples`, those files will be generated for you. Please let me know if that fixes your issue, we do need to update the documentation, but this is pre-release software.

**Comment by tolot27** [comment]
It works as suggested by @erasche. Should be documented.
