### ISSUE TITLE
Display a box representing the genome

### ISSUE THREAD

**Issue by hexylena** [TAMU-CPT/mauved3#2]
- [x] scaling function to convert genome-coordinates into svg coordinates. E.g. a genome going from (0, 10000 bases) would be converted to (0, 800 svg units, px?)
- [ ] function plot_genome(id, sequence.length), plot a box using the scaling function to determine x/y/w/h
- [ ] given  sequence data (#1), call plot_genome() with that information.

**Comment by elenimijalis** [comment]
in 130e499dda3e39297688dc152f3c7f86805b1db2

not exactly as outlined above, but can be easily adjusted I guess
