### ISSUE TITLE
Load GFF3 data

### ISSUE THREAD

**Issue by hexylena** [TAMU-CPT/mauved3#3]
- [x] console.log() all top level features. I'm not sure how biojs-io-gff3 behaves, if it does hierarchy right then easy to loop over top level. If it is just a flat feature list, then you may wish to filter based on whether the feature type == (gene, tRNA, terminator).
- [x] use the function from #2 to plot the genes in the right location (don't worry about overlaps or anything)

**Comment by elenimijalis** [comment]
closed 00028f7578a111b7e83c210ab41c707ea152b48e
